### ISSUE TITLE
Added repo doesn't get pull requests

### ISSUE THREAD

**Issue by albuch** [fthomas/scala-steward#1011]
Hi, 
I've added https://github.com/albuch/sbt-dependency-check to https://github.com/scala-steward-org/repos/pull/10 4 days ago, but haven't received any pull requests yet where other repos that we're added just hours ago already got pull requests.
Is there something wrong?
I would expect to get request for slf4j, sbt-sontatype etc.

**Comment by fthomas** [comment]
I just checked the logs and indeed there is an error while running the `dependencyUpdates` task from sbt-updates in your repo:
```
[info] Found 2 dependency updates for sbt-dependency-check
[info]   commons-collections:commons-collections : 3.2.2            -> 20040102.233541
[info]   org.slf4j:slf4j-simple                  : 1.7.25 -> 1.7.28
java.lang.RuntimeException: Dependency updates found
        at scala.sys.package$.error(package.scala:27)
        at com.timushev.sbt.updates.Reporter$.displayDependencyUpdates(Reporter.scala:131)
        at com.timushev.sbt.updates.UpdatesPlugin$$anonfun$7.apply(UpdatesPlugin.scala:37)
        at com.timushev.sbt.updates.UpdatesPlugin$$anonfun$7.apply(UpdatesPlugin.scala:36)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (*:dependencyUpdates) Dependency updates found
```
The exception is thrown [here](https://github.com/rtimush/sbt-updates/blob/0.4.2/src/main/scala/com/timushev/sbt/updates/Reporter.scala#L131) and it seems that is because `dependencyUpdatesFailBuild` is set to `true`. Interesting, I've not encountered this option before. I guess Scala Steward should set this option to `false` in its sbt sessions.
