### ISSUE TITLE
strange stack when running steward

### ISSUE THREAD

**Issue by tyrcho** [fthomas/scala-steward#1028]
I'm using scala-steward for a while on a dozen projects in my company, with great satisfaction.

Since a few days, the updates on only one project (the most complex) are crashing with a strange stack trace.

The scala project is private, but the job which runs scala-steward is public in [this Gitlab repository](https://gitlab.com/colisweb-open-source/scala-steward/tree/master)

full log : https://gitlab.com/colisweb-open-source/scala-steward/-/jobs/315753526

```
at org.scalasteward.core.io.process$.$anonfun$slurp$11(process.scala:54)
	at cats.syntax.FlatMapOps$.$anonfun$$greater$greater$1(flatMap.scala:33)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:366)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.ForwardCancelable.loop$1(ForwardCancelable.scala:46)
	at cats.effect.internals.ForwardCancelable.$anonfun$cancel$1(ForwardCancelable.scala:52)
	at cats.effect.internals.ForwardCancelable.$anonfun$cancel$1$adapted(ForwardCancelable.scala:52)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:341)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:119)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by tyrcho** [comment]
We are using the latest scala-steward docker image, so it could be triggered either a change in steward or a change in our source code.

The most annoying at the moment is that the error is unclear (truncated stack trace) so it's difficult to understand the underlying issue.

**Comment by fthomas** [comment]
The stack trace is not truncated it is just that the message of that exception is very long because it contains the whole output of the sbt command that caused the exception. The first line of the exception is:
```
java.util.concurrent.TimeoutException: 'sbt -batch -no-colors ;set every dependencyUpdatesFailBuild := false;dependencyUpdates;reload plugins;dependencyUpdates' timed out after 10 minutes
```
Maybe increasing the timeout with `--process-timeout` helps.

**Comment by tyrcho** [comment]
thanks a lot, I'll try with 30 min !

**Comment by tyrcho** [comment]
it seems to work better. scalafix migrations for `org.scalacheck:scalacheck:test : 1.14.0 -> 1.14.2` seem to  be taking ages ...

**Comment by tyrcho** [comment]
if someone else reads this issue, the proper syntax is
`--process-timeout 30min`

see for example https://gitlab.com/colisweb-open-source/scala-steward/blob/develop/steward.sh

**Comment by fthomas** [comment]
If finding the proper syntax for the timeout option is not straightforward, we could add a hint like `"Try increasing the timeout with --process-timeout ${timeout * 2}"` to the message of that exception. And maybe we should increase the default timeout.

We could also improve the formatting of the exception message if it too long. Ideas welcome!
