### ISSUE TITLE
Got OutOfMemoryError Error when running scala-steward from docker image in AWS codebuild

### ISSUE THREAD

**Issue by tanvn** [fthomas/scala-steward#1437]
I have a codebuild AWS with 7GB RAM (BUILD_GENERAL1_MEDIUM)
And the command to run scala-steward is like 

```
    docker run -m=4g --rm scala-steward-fo-my-repo:latest \
      -DLOG_LEVEL=DEBUG \
      --workspace  "/opt/scala-steward/workspace" \
      --repos-file "/opt/scala-steward/repos.md" \
      --git-author-email XXX  \
      --vcs-api-host "https://api.github.com" \
      --vcs-login  abc \
      --git-ask-pass "/opt/scala-steward/token.sh" \
      --do-not-fork \
      --process-timeout 90min
``` 
then I got the below error,  if you know how this could be fixed, please let me know. 
I am searching for the solution.

```

java.lang.OutOfMemoryError: GC overhead limit exceeded
--
471 | at sbt.Info.copy(Action.scala:76)
472 | at sbt.Info.set(Action.scala:85)
473 | at sbt.internal.Load$.setDefinitionKey(Load.scala:312)
474 | at sbt.internal.Load$.$anonfun$finalTransforms$1(Load.scala:295)
475 | at sbt.internal.Load$$$Lambda$1737/646148183.apply(Unknown Source)
476 | at sbt.internal.util.Init$Setting.$anonfun$mapInit$1(Settings.scala:621)
477 | at sbt.internal.util.Init$Setting$$Lambda$1722/926188689.apply(Unknown Source)
478 | at scala.Function1.$anonfun$compose$1(Function1.scala:49)
479 | at scala.Function1$$Lambda$921/1154481189.apply(Unknown Source)
480 | at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:223)
481 | at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:166)
482 | at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
483 | at sbt.internal.util.EvaluateSettings$$Lambda$1841/897303688.apply$mcV$sp(Unknown Source)
484 | at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
485 | at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
486 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
487 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
488 | at java.lang.Thread.run(Thread.java:748)
489 | [error] [launcher] error during sbt launcher: java.lang.OutOfMemoryError: GC overhead limit exceeded
490 |  
491 | at org.scalasteward.core.io.process$.$anonfun$slurp$10(process.scala:49)
492 | at org.scalasteward.core.io.process$.$anonfun$slurp$10$adapted(process.scala:45)
493 | at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:145)
494 | at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
495 | at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
496 | at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
497 | at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
498 | at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
499 | at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
500 | at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
501 | at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
502 | at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
503 | at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
504 | at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
505 | at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
506 | at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
507 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
508 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
509 | at java.lang.Thread.run(Thread.java:748)

```

**Comment by tanvn** [comment]
adding 
```
--env-var "SBT_OPTS=-Xmx7168m -Xss1024m -XX:MaxMetaspaceSize=512m"
```
helped me solve the problem !

Thank you guys so much !
