### ISSUE TITLE
Feature request: unexpected HTTP status: 401, tell which url

### ISSUE THREAD

**Issue by robstoll** [fthomas/scala-steward#684]
I currently get the following error
```
scala.MatchError: org.http4s.client.UnexpectedStatus: unexpected HTTP status: 401 Unauthorized (of class org.http4s.client.UnexpectedStatus)
	at org.scalasteward.core.gitlab.http4s.Http4sGitLabApiAlg.$anonfun$createFork$1(Http4sGitlabApiAlg.scala:121)
	at cats.effect.internals.IOFrame$ErrorHandler.recover(IOFrame.scala:51)
	at cats.effect.internals.IOFrame$ErrorHandler.recover(IOFrame.scala:48)
```
It is certainly a configuration error on my part. Yet, it would be nice to see what request caused this error (at least URL, maybe even API including header, content etc.)

**Comment by fthomas** [comment]
This is a duplicate of #668.

**Comment by robstoll** [comment]
Hood
