### ISSUE TITLE
Steward does not handle cleanly the case where its MR was merged

### ISSUE THREAD

**Issue by tyrcho** [fthomas/scala-steward#743]
here is the log:

```
2019-07-19 11:07:44,536 INFO  ──────────── Nurture colisweb-open-source/JRubysnessHours ────────────
2019-07-19 11:07:44,536 INFO  Clone and synchronize colisweb-open-source/JRubysnessHours
2019-07-19 11:07:44,991 INFO  Find updates for colisweb-open-source/JRubysnessHours
2019-07-19 11:09:10,854 INFO  Ignore org.scala-lang:scala-library:provided : 2.12.7 -> 2.12.8 -> 2.13.0 (reason: ignored globally)
2019-07-19 11:09:10,855 INFO  Ignore org.scala-lang:scala-library : 2.12.8 -> 2.13.0 (reason: ignored globally)
2019-07-19 11:09:10,867 INFO  Found 10 updates:
  com.geirsson:sbt-scalafmt : 1.6.0-RC1 -> 1.6.0-RC4
  com.github.gseitz:sbt-release : 1.0.10 -> 1.0.11
  com.github.writethemfirst:approvals-java:test : 0.7.0 -> 0.7.2 -> 0.9.0
  com.lihaoyi:pprint:test : 0.5.3 -> 0.5.5
  com.rallyhealth:scalacheck-ops_1-14:test : 2.2.0 -> 2.2.1
  com.timushev.sbt:sbt-updates : 0.3.4 -> 0.4.2
  io.github.davidgregory084:sbt-tpolecat : 0.1.5 -> 0.1.7
  org.foundweekends:sbt-bintray : 0.5.4 -> 0.5.5
  org.scalatest:scalatest:test : 3.0.7 -> 3.0.8
  org.scoverage:sbt-scoverage : 1.5.1 -> 1.6.0
2019-07-19 11:09:10,887 INFO  Process update com.geirsson:sbt-scalafmt : 1.6.0-RC1 -> 1.6.0-RC4
2019-07-19 11:09:11,154 INFO  Found PR https://gitlab.com/colisweb-open-source/JRubysnessHours/merge_requests/1
2019-07-19 11:09:11,237 INFO  PR is up-to-date with master
2019-07-19 11:09:11,286 INFO  Process update com.github.gseitz:sbt-release : 1.0.10 -> 1.0.11
2019-07-19 11:09:11,427 INFO  Found PR https://gitlab.com/colisweb-open-source/JRubysnessHours/merge_requests/3
2019-07-19 11:09:11,498 INFO  PR is up-to-date with master
2019-07-19 11:09:11,532 INFO  Process update com.github.writethemfirst:approvals-java:test : 0.7.0 -> 0.7.2 -> 0.9.0
2019-07-19 11:09:11,664 INFO  Found PR https://gitlab.com/colisweb-open-source/JRubysnessHours/merge_requests/4
2019-07-19 11:09:11,737 INFO  PR is up-to-date with master
2019-07-19 11:09:11,750 INFO  Process update com.lihaoyi:pprint:test : 0.5.3 -> 0.5.5
2019-07-19 11:09:11,860 INFO  Found PR https://gitlab.com/colisweb-open-source/JRubysnessHours/merge_requests/5
2019-07-19 11:09:11,914 INFO  PR is up-to-date with master
2019-07-19 11:09:11,933 INFO  Process update com.rallyhealth:scalacheck-ops_1-14:test : 2.2.0 -> 2.2.1
2019-07-19 11:09:12,129 INFO  Found PR https://gitlab.com/colisweb-open-source/JRubysnessHours/merge_requests/6
2019-07-19 11:09:12,197 INFO  PR is up-to-date with master
2019-07-19 11:09:12,220 INFO  Process update com.timushev.sbt:sbt-updates : 0.3.4 -> 0.4.2
2019-07-19 11:09:12,442 INFO  Found PR https://gitlab.com/colisweb-open-source/JRubysnessHours/merge_requests/7
2019-07-19 11:09:12,487 INFO  PR is up-to-date with master
2019-07-19 11:09:12,504 INFO  Process update io.github.davidgregory084:sbt-tpolecat : 0.1.5 -> 0.1.7
2019-07-19 11:09:12,724 INFO  Found PR https://gitlab.com/colisweb-open-source/JRubysnessHours/merge_requests/8
2019-07-19 11:09:12,772 INFO  PR is up-to-date with master
2019-07-19 11:09:12,789 INFO  Process update org.foundweekends:sbt-bintray : 0.5.4 -> 0.5.5
2019-07-19 11:09:12,964 INFO  Found PR https://gitlab.com/colisweb-open-source/JRubysnessHours/merge_requests/9
2019-07-19 11:09:13,020 INFO  PR is up-to-date with master
2019-07-19 11:09:13,041 INFO  Process update org.scalatest:scalatest:test : 3.0.7 -> 3.0.8
2019-07-19 11:09:13,197 ERROR ──────────── Nurture colisweb-open-source/JRubysnessHours ──────────── failed
org.http4s.InvalidMessageBodyFailure: Invalid message body: Could not decode JSON: [
  {
    "id" : 33512486,
    "iid" : 10,
    "project_id" : 12690806,
    "title" : "Update scalatest to 3.0.8",
    "description" : "Updates org.scalatest:scalatest from 3.0.7 to 3.0.8.\n\nI'll automatically update this PR to resolve conflicts as long as you don't change it yourself.\n\nIf you'd like to skip this version, you can just close this PR. If you have any feedback, just mention @tyrcho in the comments below.\n\nHave a fantastic day writing Scala!\n\n<details>\n<summary>Ignore future updates</summary>\n\nAdd this to your `.scala-steward.conf` file to ignore future updates of this dependency:\n```\nupdates.ignore = [{ groupId = \"org.scalatest\", artifactId = \"scalatest\" }]\n```\n</details>\n\nlabels: semver-patch",
    "state" : "merged",
    "created_at" : "2019-07-19T09:35:34.999Z",
    "updated_at" : "2019-07-19T11:08:02.445Z",
    "merged_by" : {
      "id" : 188924,
      "name" : "Michel Daviot",
      "username" : "tyrcho",
      "state" : "active",
      "avatar_url" : "https://secure.gravatar.com/avatar/6f8ce479259114a0872c3158d0cf9831?s=80&d=identicon",
      "web_url" : "https://gitlab.com/tyrcho"
    },
    "merged_at" : "2019-07-19T11:08:02.503Z",
    "closed_by" : null,
    "closed_at" : null,
    "target_branch" : "master",
    "source_branch" : "update/scalatest-3.0.8",
    "user_notes_count" : 0,
    "upvotes" : 0,
    "downvotes" : 0,
    "assignee" : null,
    "author" : {
      "id" : 188924,
      "name" : "Michel Daviot",
      "username" : "tyrcho",
      "state" : "active",
      "avatar_url" : "https://secure.gravatar.com/avatar/6f8ce479259114a0872c3158d0cf9831?s=80&d=identicon",
      "web_url" : "https://gitlab.com/tyrcho"
    },
    "assignees" : [
    ],
    "source_project_id" : 12690806,
    "target_project_id" : 12690806,
    "labels" : [
    ],
    "work_in_progress" : false,
    "milestone" : null,
    "merge_when_pipeline_succeeds" : false,
    "merge_status" : "can_be_merged",
    "sha" : "d183cef27deaf7ad574ed7c17f8f45115f0b177f",
    "merge_commit_sha" : "b783b618b7c1a53e1aa6ecf2dd191f6aa19791ed",
    "discussion_locked" : null,
    "should_remove_source_branch" : null,
    "force_remove_source_branch" : null,
    "reference" : "!10",
    "web_url" : "https://gitlab.com/colisweb-open-source/JRubysnessHours/merge_requests/10",
    "time_stats" : {
      "time_estimate" : 0,
      "total_time_spent" : 0,
      "human_time_estimate" : null,
      "human_total_time_spent" : null
    },
    "squash" : false,
    "task_completion_status" : {
      "count" : 0,
      "completed_count" : 0
    },
    "approvals_before_merge" : null
  }
]
	at org.http4s.circe.CirceInstances$.$anonfun$defaultJsonDecodeError$1(CirceInstances.scala:191)
	at org.http4s.circe.CirceInstances.$anonfun$jsonOfWithMedia$2(CirceInstances.scala:73)
	at scala.util.Either.fold(Either.scala:192)
	at org.http4s.circe.CirceInstances.$anonfun$jsonOfWithMedia$1(CirceInstances.scala:74)
	at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:99)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:366)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
	at org.http4s.client.blaze.Http1Connection.parsePrelude(Http1Connection.scala:296)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1(Http1Connection.scala:189)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1$adapted(Http1Connection.scala:188)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: io.circe.DecodingFailure$$anon$2: Unexpected string 'merged': DownField(state),DownArray
2019-07-19 11:09:13,200 INFO  ──────────── Total time: colisweb-open-source/JRubysnessHours: 1m 28s 664ms ────────────
```

**Comment by fthomas** [comment]
I think an easy fix would be to match `"merged"` [here](https://github.com/fthomas/scala-steward/blob/2d16e9d9e1e28fbaf7ed990cc770d99bf6ce3ab6/modules/core/src/main/scala/org/scalasteward/core/vcs/data/PullRequestState.scala#L31-L36) and map it to `Right(Closed)`. GitHub also uses `"closed"` as state for merged pull request, so this should do the right thing.

**Comment by tyrcho** [comment]
Makes sense ! I created a PR with this change, but I won't be able to test it properly before 2 weeks, I have a very flaky internet from here ...
